### ISSUE TITLE
CPU 100% when input data is not yet generated

### ISSUE THREAD

**Issue by lilydjwg** [lotabout/skim#123]
To demostrate:

```
cat | sk
```

And listen to your CPU fan spinning up as strong as possible.

**Comment by lotabout** [comment]
Note that the example: `cat | sk` still won't work correctly:
- It won't consume 100% CPU of course
- But you have no way to exit the program

This is because skim has no way to kill the reader thread directly(limitation of thread APIs). Also the input won't generate EOF since `cat` is waiting for user input.

I decide not to solve this issue for now, basically because I think it rarely happens in real use cases.

**Comment by lilydjwg** [comment]
Thanks. I don't need `cat | sk` to work, but only to demostrate the issue in a simple way.
