### ISSUE TITLE
Can't use interactive mode

### ISSUE THREAD

**Issue by jayong93** [lotabout/skim#126]
Hi, I tried to use Interactive mode of skim as usage in README (`sk --ansi -i -c 'ag --color "{}"'`, of course I have had `ag`) but I got an unexpected error.

The program started well but suddenly infinitly added blank space to query string. Finally it gave me the error:

> thread '<unnamed>' panicked at 'curses:write_to_term: error on writting to terminal: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', libcore/result.rs:945:5

I'm using Linux Mint 19 Tara with linux kernel 4.15.0-45-generic. And my shell is zsh with oh-my-zsh. how should I fix it?

**Comment by lotabout** [comment]
@jayong93 Thanks for report! I have several questions:

- How often does it happen?
- Which version do you use? if possible, could you please use the master branch to reproduce it?
- If possible, could you find out which file could cause this problem?

As the error message suggested, the error happens on writing to the terminal, and the reason is "Resource temporarily unavailable". I have no idea how it happened but it shouldn't happen frequently.

**Comment by jayong93** [comment]
@lotabout It happens every time I execute the program and I use 0.5.2 version skim.

I have done some tests and found interesting things. Not only interactive mode, but it add a blank on start in normal mode too. Also it works well on older version kernel (eg. 4.15.0-20).

I am going to try master branch and if there are same error, I will let you know.

**Comment by jayong93** [comment]
The master branch fix it! Thanks!
