### ISSUE TITLE
Add an option that allows only searching for directories

### ISSUE THREAD

**Issue by JimVliet** [lotabout/skim#162]
It seems like there is no option to only fuzzy search for directories (ignoring all normal files). Of course one way to do this is to use this: `find . -type d -print | sk` It would be nice though if there was a command line option for this, so that you don't have to use find.

**Comment by lotabout** [comment]
@JimVliet Thanks for your suggestion. I won't add this unfortunately, basically because skim was designed to be a general fuzzy finder. Thus I think it is better for it not to treat the input specially (e.g. files vs directories).

Though, I'll consider adding some actions for changing the input source dynamically(e.g. the `find` command).

**Comment by derrickcope** [comment]
Just use it with fd --type d
