### ISSUE TITLE
1/1 occludes preview text

### ISSUE THREAD

**Issue by nh2** [lotabout/skim#291]
I'd like to copy-pase text out of the preview window, but the `1/1` overlay text "occludes" (overrides) some of the contents:

![image](https://user-images.githubusercontent.com/399535/77236633-b141e500-6bc0-11ea-9270-17979ae0d867.png)

How can I disable the `1/1`?

In general, I've had trouble figuring out what that even is (is it some kind of page counter for the preview window?).

It would be great if the README could document what it is.

**Comment by lotabout** [comment]
@nh2 Problem understood.

> In general, I've had trouble figuring out what that even is (is it some kind of page counter for the preview window?).

It's actually `line_num/total_line_num` of the text to preview. Was designed to let user know the current offset.

As for how to fix, I don't like to have an option for every small tweak. Currently a "reasonable default" that I could come up with:
- Do not show the pager if the content could fit the window.
- Do not show the pager if the offset is 0.
- Show the pager otherwise.

**Comment by lotabout** [comment]
The final solution is a bit different to what's described above: the offset would still be shown if the content could not fit into the window event when the offset is 0.

**Comment by nh2** [comment]
@lotabout Would you mind posting a screenshot of your solution?

My problem is not that a pager is shown when not needed, but that

* I cannot read the characters below the `1/1` (which is important to figure out whether that's the line I want to select or not)
* I cannot copy-paste the contents of the preview window out.

These might be fixed trivially by moving the pager one row up, to be part of the "separator" line.
