### ISSUE TITLE
skim does not prioritize exact match

### ISSUE THREAD

**Issue by issadarkthing** [lotabout/skim#320]
skim
![image](https://user-images.githubusercontent.com/50593529/84051926-6cb92f00-a9e2-11ea-8309-26947093f300.png)

fzf
![image](https://user-images.githubusercontent.com/50593529/84052010-8e1a1b00-a9e2-11ea-8fcc-6d04318dc686.png)

**Comment by lotabout** [comment]
@issadarkthing Thanks for report.

* If what you'd like to do is exact matching, try the `'keyword` syntax. Or in your case you could type `node$` for suffix matching.
* For the algorithm, currently skim's algorithm did not apply such heuristic knowledge and will not before more investigation. Besides:
    * All these cases are "exact match"
    * I believe fzf gives more weights on the prefix and suffix match
    * And I'm not sure if it is a good choice for all times.

**Comment by resolritter** [comment]
The issue is misleading. The behavior shown in the picture is due to the `tiebreak` FZF option which defaults to "length".

https://github.com/junegunn/fzf/blob/43798fc2e801f4c5e6b9c3d048fb09eb8c7b6401/src/options.go#L38

i.e. since all got the exact match, due to this `tiebreak` rule, the shortest one got sorted first.

---

Skim already supports this option, although it does **not** select `length` by default, like FZF does.

https://github.com/lotabout/skim/blob/2241315a90c6f5caec4bc7d03e6ca951a9202ce2/src/selection.rs#L25-L26

Therefore it's Skim's default choice rather than a bug. You should be able to match FZF's behavior by configuring the tiebreak rule to your liking.
