### ISSUE TITLE
How do I use it with vim (ctrl-p)?

### ISSUE THREAD

**Issue by Phrohdoh** [lotabout/skim#36]
Because let's be honest this is where fuzzy-file-finding saves us the most time. :-)

**Comment by gezpage** [comment]
Just use `:SK` to open the fuzzy finder and away you go!

**Comment by CallumHoward** [comment]
I'm having some issues using https://github.com/lotabout/skim.vim (seems like there is no issue tracker for GH forks?)
When trying `:SK` i get `E492: Not an editor command: SK` and when trying `:Files` , I get
```
Error detected while processing function skim#vim#files[13]..<SNR>82_skim:
line    5:
E117: Unknown function: skim#run
E15: Invalid expression: skim#run(merged)
```

I'm using neovim v0.2.0-4-g9e56278 on macOS Sierra, installed `lotabout/skim.vim` using `dein`.

**Comment by lotabout** [comment]
@CallumHoward You would need to install `skim` in order to use `skim.vim`.

Sorry I don't use `dein`, here is the `vim-plug`'s version:

```
    Plug 'lotabout/skim', { 'dir': '~/.skim', 'do': './install' }
    Plug 'lotabout/skim.vim'
```

- `skim` itself contains the `:SK` command and `skim#run` function
- While `skim.vim` contains other utilities built upon `skim`, including `:Files`, `:Buffers`, etc.

Note however that `skim.vim` is only a fork that I use for myself. Currently I don't have time to maintain it.

**Comment by CallumHoward** [comment]
Thanks, I was able to get it working with the above information and also with [this comment](https://github.com/Shougo/dein.vim/issues/74#issuecomment-237198717).
I ended up with the following:
```
call dein#add('lotabout/skim', { 'build': './install --all', 'merged': 0 })
call dein#add('lotabout/skim.vim', { 'depends': 'skim' })
```

**Comment by lotabout** [comment]
Close because I think the thread contains enough information to solve the issue. Reopen if you need more.
