### ISSUE TITLE
Add --height flag a la fzf?

### ISSUE THREAD

**Issue by ErichDonGubler** [lotabout/skim#54]
See [here](https://github.com/junegunn/fzf#layout).

**Comment by lotabout** [comment]
@ErichDonGubler Thanks for the suggestion!

Would you please show me some use cases of this feature? I myself cannot see why this is necessary.

**Comment by ErichDonGubler** [comment]
"Necessary" is a strong word, seeing that this is a feature request. I'm not familiar with your design goals. However, consider the difference in flow:

![animation](https://s30.postimg.org/gqo6ypdxd/fzf_height.gif)

What `--height` does in `fzf` is disable full-screen behavior and puts fuzzy-finder search UI into the terminal  inline. It's far more friendly to flow when a tool like `sk` *doesn't* break flow by rendering over the whole screen. I use fuzzy-finding tools in my own Bash scripts, and it's helpful to be able to view previous output while using the finding UI.

**Comment by lotabout** [comment]
It's been a lot of time since the issue was opened. It was until recently that I got time to investigate how to implement this feature. Yet it is bad new here.

1. `ncurese` will erase the content when it is initialized. That means as long as `skim` use ncurses, this feature cannot be implemented.
2. I do found a library [termion](https://github.com/ticki/termion) that support this feature (won't erase all contents). But termion is not yet ready to replace ncurses in skim, for example:
    - termion assume stdin to be a `tty`. It is not true when we invoke like `echo 'aa' | sk`.

So I would suspend this ticket till termion is ready or there are some other suitable libraries.

**Comment by lotabout** [comment]
Now this feature is added in the `master` branch. I use [termion](https://github.com/ticki/termion) to implement it.

It is actually a big change to replace ncurses-rs with termion. More test is necessary.
