### ISSUE TITLE
diff-so-fancy in preview is not rendered properly

### ISSUE THREAD

**Issue by magnetophon** [lotabout/skim#72]
I have some commands that preview git diffs trough [diff-so-fancy](https://github.com/so-fancy/diff-so-fancy), but they are not rendered properly.

Example command:
```
fshow () {
	git log --color=always --format="%C(auto)%h%d %s %C(black)%C(bold)%cr% C(auto)%an" "$@" | sk --ansi --reverse --tiebreak=index --no-multi --preview $_viewGitLogLine --header "enter to view, alt-y to copy hash" --bind "enter:execute:$_viewGitLogLine   | less -R" --bind "alt-y:execute:$_gitLogLineToHash | xclip"
}

_viewGitLogLine="echo {} | grep -o '[a-f0-9]\{7\}' | head -1 | xargs -I % sh -c 'git show --color=always %' | diff-so-fancy"

$_gitLogLineToHash="echo {} | grep -o '[a-f0-9]\{7\}' | head -1"
```

Output with fzf vs with sk:
https://imgur.com/a/CL1XO

**Comment by lotabout** [comment]
@magnetophon I checked the image you attached, and I think `skim` renders properly while `fzf` does not.

If possible, please attach the raw output(image) by `diff-so-fancy`.

**Comment by magnetophon** [comment]
@lotabout I don't understand. The lines above and below the modified file are interrupted by skim.
fzf renders them like the [screenshot](https://user-images.githubusercontent.com/3429760/32387617-44c873da-c082-11e7-829c-6160b853adcb.png) on the project page.

In the images I originally linked, the first one is fzf, the second skim.

**Comment by lotabout** [comment]
@magnetophon Oh, now I see the problem. I thought it was the highlighted content.
I'll have a check.

**Comment by lotabout** [comment]
The root cause of this issue is the width calculation of character `─`. There are some characters that are ambiguous in the columns that they occupies according to [Unicode® Standard Annex #11](http://www.unicode.org/reports/tr11/).

skim use the crate [unicode-width](https://unicode-rs.github.io/unicode-width/unicode_width/trait.UnicodeWidthChar.html) to calculate the columns. And previously it use `width_cjk()` which will treat the ambiguous characters as `2` columns, thus causing the "separation".
Now I decide to use `width()` which will treat them as `1` column. I think it make sense since the normal use-case will be under non-CJK context.

**Comment by magnetophon** [comment]
Great, thanks!
