### ISSUE TITLE
skim panic - attempt to unwrap None value

### ISSUE THREAD

**Issue by bryaan** [lotabout/skim#78]
Using a function like this and selecting some process (just tried random until it broke) as skims' selection produces a panic:

```
$ fkill
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', 27
```

```
function fkill -d 'fuzzy kill processes'
  ps -ef | sed 1d | sk --multi
end
```

**Comment by lotabout** [comment]
@bryaan How frequent does this problem occur? I tried it over 100 times and cannot reproduce it.

Actually I've met this problem some times, but the frequency is quite low I could not find the correct way to reproduce it, thus finally give up to fix it. But if you have some "stable" way to reproduce it, I'll fix it.

**Comment by bryaan** [comment]
@lotabout Pretty often, but I don't see any LCD.  There aren't any obvious issues in the code that parses inputs?  It really looks like that is where it's at - ohhhhhh maybe, just maybe, it has to do with my Nerd Fonts Hack font.  Try using that! Maybe the parser is choking on some wierd character?

Secondly, can you point me to the line and file where this error is occurring? If not, then the first step is  to add some debug info so I can report back, since you don't seem to be experiencing the issue.

It definitely is concerning a Rust program, and a system level one like this, is failing in such a way.  We need to fix this.

**Comment by bryaan** [comment]
Have you tested for the possibility of empty strings? Isn't that what the error is saying?

**Comment by lotabout** [comment]
@bryaan sorry for late reply, I was on a vacation.

Thanks for all the investigation, but the location you point out has relatively low possibility to be the root cause. Otherwise we could reproduce it all the time.

Since the issue happens randomly, I suspect it is related with process creation or something like that. e.g. we need to call `find` and pass the input to other thread of skim, it might be some error on invoking `find`.

Anyway, I'll try to reproduce it. (add log to all `unwrap` and find out what's going on)

**Comment by lotabout** [comment]
@bryaan I've added logs for `expect`s, would you please use branch [issue-78](https://github.com/lotabout/skim/tree/issue-78) and try to log the output on panic? I still failed to reproduce it. Thanks!

**Comment by bryaan** [comment]
@lotabout I'm so sorry but I no longer have that machine.  If it happens again on another one I will post back.

**Comment by lotabout** [comment]
Close. Feel free to reopen if it appears again.
